<a href="https://colab.research.google.com/github/cmvigneswaranaero-gif/space_lab/blob/main/PYTHON_FOR_AEROSPACE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTHON FOR AEROSPACE**

# ***DEFINING VARIABLES***



In [1]:
# Define variables
velocity = 30
pressure = 1250.567

print(velocity)
print (pressure)

# Check datatypes
print(type(velocity))
print(type(pressure))

# Print with labels
print("Velocity - datatype:", type(velocity))
print("Pressure - datatype:", type(pressure))

30
1250.567
<class 'int'>
<class 'float'>
Velocity - datatype: <class 'int'>
Pressure - datatype: <class 'float'>


In [2]:
# Defining fluid properties for air
air_density = 1.225       # Air density in kg/m^3
air_viscosity = 1.81e-5   # Air viscosity in Pa.s

# Printing the results
print("Air density:", air_density, "kg/m^3")
print("Air viscosity:", air_viscosity, "Pa.s")


Air density: 1.225 kg/m^3
Air viscosity: 1.81e-05 Pa.s


# ***STRING***

In [3]:
# Defining a string
AIRCRAFT = "BOEING_747"
print(AIRCRAFT)

# Accessing characters and substrings
print(AIRCRAFT[0])      # First character
print(AIRCRAFT[0:3])    # Characters from index 0 to 2
print(AIRCRAFT[3:8])    # Characters from index 3 to 7
print(AIRCRAFT[3:4])    # Character at index 3

BOEING_747
B
BOE
ING_7
I


In [4]:
# Defining a string
message = "Python for Aerospace Engineering"
print(message)

# Accessing part of the string
print(message[0:6])     # Characters from index 0 to 5

# Length of the string
print(len(message))


Python for Aerospace Engineering
Python
32


In [5]:
# Defining strings
First_name = "Aerospace"
Last_name = "Engineering"

# Concatenation without space
Name = First_name + Last_name
print(Name)

# Concatenation with space
Name_new = First_name + " " + Last_name
print(Name_new)

# Repetition
print(Name_new * 3)

# Repetition with space
print((Name_new + " ") * 3)


AerospaceEngineering
Aerospace Engineering
Aerospace EngineeringAerospace EngineeringAerospace Engineering
Aerospace Engineering Aerospace Engineering Aerospace Engineering 


# **Boolean**

In [6]:
# Check if velocity exceeds speed of sound
velocity = 250     # m/s
speed_of_sound = 343  # m/s at sea level

a = velocity > speed_of_sound   # Boolean condition
print(a)                        # Prints True/False
print(type(a))                  # Prints datatype


False
<class 'bool'>


In [7]:
# Example: Check if aircraft is supersonic
velocity = 250        # m/s
speed_of_sound = 343  # m/s at sea level
a = velocity > speed_of_sound
if a:
    print("Supersonic")
else:
    print("Subsonic")


Subsonic


# **LIST**

In [8]:
# Creating lists for aircraft and max speeds
aircraft = ["Boeing_747", "Airbus_A320", "Cessna_172"]
max_speed = [920, 840, 302]   # speeds in km/h

# Printing the lists
print(aircraft)
print(max_speed)

# Accessing list elements
print(aircraft[0])    # First aircraft
print(max_speed[1])   # Max speed of second aircraft

['Boeing_747', 'Airbus_A320', 'Cessna_172']
[920, 840, 302]
Boeing_747
840


In [9]:
# Adding more aircraft
new_aircraft = ["F-16", "Concorde"]
all_aircraft = aircraft + new_aircraft
print(all_aircraft)
print(len(all_aircraft))   # Total number of aircraft

# Appending a new aircraft
all_aircraft.append("SR-71")
print(all_aircraft)

# Deleting an aircraft
del all_aircraft[2]   # Deletes "Cessna_172"
print(all_aircraft)

['Boeing_747', 'Airbus_A320', 'Cessna_172', 'F-16', 'Concorde']
5
['Boeing_747', 'Airbus_A320', 'Cessna_172', 'F-16', 'Concorde', 'SR-71']
['Boeing_747', 'Airbus_A320', 'F-16', 'Concorde', 'SR-71']


In [10]:
# Creating lists for aircraft and max speeds
aircraft = ["Boeing_747", "Airbus_A320", "Cessna_172"]
max_speed = [920, 840, 302]   # speeds in km/h

# Accessing elements using negative index
print("Last aircraft:", aircraft[-1])         # Cessna_172
print("Second last aircraft:", aircraft[-2])  # Airbus_A320
print("Last speed:", max_speed[-1])           # 302
print("Second last speed:", max_speed[-2])    # 840

# Adding new aircraft and using negative index
new_aircraft = ["F-16", "Concorde"]
all_aircraft = aircraft + new_aircraft
print("Last aircraft in combined list:", all_aircraft[-1])   # Concorde
print("Second last aircraft in combined list:", all_aircraft[-2])  # F-16

Last aircraft: Cessna_172
Second last aircraft: Airbus_A320
Last speed: 302
Second last speed: 840
Last aircraft in combined list: Concorde
Second last aircraft in combined list: F-16


In [11]:
# LIST WITH MIXED DATA
# List of integer velocities (m/s)
velocities = [250, 340, 120]  # int type elements
print("Velocities:", velocities)

# List of float pressures (Pa)
pressures = [101325.0, 100800.5, 100500.2]  # float type elements
print("Pressures:", pressures)

# List of flow types
flow_types = ["laminar", "turbulent", "transitional"]  # str type elements
print("Flow types:", flow_types)

# List with mixed data types (example: sensor reading, fluid type, pressure)
mixed_data = [3.5, "air", 101325]  # float, str, int
print("Mixed data:", mixed_data)


Velocities: [250, 340, 120]
Pressures: [101325.0, 100800.5, 100500.2]
Flow types: ['laminar', 'turbulent', 'transitional']
Mixed data: [3.5, 'air', 101325]


# **TUPLE**

In [12]:
# --- Tuple Example (Immutable Data) ---
# Aircraft properties: (wing_span,fuselage_length,takeoff_weight )
aircraft_properties = (60.3, 70.6, 396890)  # fixed and constant
print("Aircraft Properties (Tuple):", aircraft_properties)

# You cannot change tuple elements
# aircraft_properties[0] = 61.0  # ❌ This will cause an error


Aircraft Properties (Tuple): (60.3, 70.6, 396890)


In [13]:
# --- Tuple Example (Immutable Data) ---
# Pipe properties: (diameter in m, length in m, roughness in mm)
pipe_properties = (0.5, 10, 0.05)  # fixed and constant
print("Pipe Properties (Tuple):", pipe_properties)

# Accessing individual elements
print("Diameter (m):", pipe_properties[0])
print("Length (m):", pipe_properties[1])
print("Roughness (mm):", pipe_properties[2])

# Trying to modify a tuple element will cause an error
# pipe_properties[0] = 0.6  # ❌ Not allowed, tuples are immutable


Pipe Properties (Tuple): (0.5, 10, 0.05)
Diameter (m): 0.5
Length (m): 10
Roughness (mm): 0.05


# **Dictionary**

In [14]:
# Defining a dictionary for air properties
air_properties = {
    "density": 1.225,        # kg/m^3
    "viscosity": 1.81e-5,    # Pa.s
    "specific_heat": 1005     # J/(kg·K)
}

# Accessing values using keys
print("Air density:", air_properties["density"], "kg/m^3")
print("Air viscosity:", air_properties["viscosity"], "Pa.s")
print("Specific heat:", air_properties["specific_heat"], "J/(kg·K)")

# Adding a new property
air_properties["pressure"] = 101325
print("Updated Air Properties:", air_properties)


Air density: 1.225 kg/m^3
Air viscosity: 1.81e-05 Pa.s
Specific heat: 1005 J/(kg·K)
Updated Air Properties: {'density': 1.225, 'viscosity': 1.81e-05, 'specific_heat': 1005, 'pressure': 101325}


In [15]:
# Define dictionary for air properties
air_properties = {
    "density": 1.225,
    "viscosity": 1.81e-5,
    "specific_heat": 1005
}

#  Change the value of an existing key
air_properties["density"] = 1.2   # Updated density
print("Updated density:", air_properties["density"])

#  Add a new key-value pair
air_properties["pressure"] = 101325
print("Added pressure:", air_properties["pressure"])

#  Change a key (create new key and delete old one)
air_properties["air_density"] = air_properties.pop("density")
print("Changed key from 'density' to 'air_density':", air_properties)


Updated density: 1.2
Added pressure: 101325
Changed key from 'density' to 'air_density': {'viscosity': 1.81e-05, 'specific_heat': 1005, 'pressure': 101325, 'air_density': 1.2}


# ***Function***

In [16]:
# Function to calculate Lift Force
def lift (density, velocity, wing_area, Cl):
    """
    Calculates Lift Force using the formula:
    L = 0.5 * density * velocity^2 * wing_area * Cl
    """
    return 0.5 * density * velocity**2 * wing_area * Cl

"""
If the function call and print statement are on the same line as the return,
which will cause an indentation error
"""
# Call the function
lift_force = lift(1, 200, 25, 1)
print("Lift Force (N):", lift_force)


Lift Force (N): 500000.0


In [17]:
# Function to calculate Reynolds Number
def reynolds_number(rho, V, L, mu):
    return (rho * V * L) / mu

# Function to calculate Dynamic Pressure
def dynamic_pressure(rho, V):
    return 0.5 * rho * V**2


# Call the functions
Re = reynolds_number(1.225,50, 0.5, 1.81e-5)
q = dynamic_pressure(1.225, 50)

# Print results
print("Reynolds Number:", Re)
print("Dynamic Pressure (Pa):", q)


Reynolds Number: 1691988.9502762433
Dynamic Pressure (Pa): 1531.25


# ***if-else***

In [18]:
Mach = 0.6   # Example Mach number

if Mach < 1:
    print("Subsonic flow")

Subsonic flow


In [19]:
Mach = 1.2

if Mach < 1:
    print("Subsonic flow")
else:
    print("Supersonic flow")


Supersonic flow


In [20]:
Mach = 2

if Mach < 1:
    print("Subsonic flow")
elif Mach == 1:
    print("Sonic flow")
else:
    print("Supersonic flow")

Supersonic flow


In [21]:
Mach = 1.2

if Mach < 0.8:
    print("Subsonic flow")
elif Mach >= 0.8 and Mach < 1.2:
    print("Transonic flow")
elif Mach >= 1.2 and Mach < 5:
    print("Supersonic flow")
else:
    print("Hypersonic flow")


Supersonic flow


In [22]:
Mach = 300000
if Re < 5e5:
    print("Flow is Laminar")
else:
    print("Flow is Turbulent")

Flow is Turbulent


# **for loop**

In [23]:
velocities = [10, 20, 30]

# 1. Basic for ... in list
for V in velocities:
    print(f"Velocity = {V} m/s")

# 2. Using enumerate() (index + value)
for i, V in enumerate(velocities):
    print(f"Case {i+1}: Velocity = {V} m/s")

# 3. Using range(start, stop, step)
for V in range(10, 40, 10):   # from 10 to 30 with step 10
    print(f"Velocity = {V} m/s")


Velocity = 10 m/s
Velocity = 20 m/s
Velocity = 30 m/s
Case 1: Velocity = 10 m/s
Case 2: Velocity = 20 m/s
Case 3: Velocity = 30 m/s
Velocity = 10 m/s
Velocity = 20 m/s
Velocity = 30 m/s


In [24]:
#  Lift Calculation with different velocities

# Constants
rho = 1.225   # air density (kg/m^3) at sea level
S = 20.0      # wing area (m^2)
CL = 0.5      # lift coefficient

# Velocity range (in m/s)
velocities = [30, 40, 50, 60, 70, 80]

# Calculate lift for each velocity using for loop
for V in velocities:
    L = 0.5 * rho * V**2 * S * CL
    print(f"Velocity: {V} m/s --> Lift: {L:.2f} N")
#f-string (formatted string literal).
#It allows us to insert variable values directly inside a string by writing them in curly braces { }.

Velocity: 30 m/s --> Lift: 5512.50 N
Velocity: 40 m/s --> Lift: 9800.00 N
Velocity: 50 m/s --> Lift: 15312.50 N
Velocity: 60 m/s --> Lift: 22050.00 N
Velocity: 70 m/s --> Lift: 30012.50 N
Velocity: 80 m/s --> Lift: 39200.00 N


In [25]:
# Reynolds number calculation
V = 2.0          # velocity (m/s)
D = 0.05         # pipe diameter (m)
mu = 0.001       # viscosity of water (Pa·s)

# Different fluid densities (kg/m^3)
densities = [800, 900, 1000, 1100, 1200]

# Calculate Reynolds number for each density
# Don’t reuse the same name for the list and the loop variable. Use something like for r in rho:
for rho in densities:
    Re = (rho * V * D) / mu
    print(f"Density: {rho} kg/m^3 --> Reynolds Number: {Re:.0f}")


Density: 800 kg/m^3 --> Reynolds Number: 80000
Density: 900 kg/m^3 --> Reynolds Number: 90000
Density: 1000 kg/m^3 --> Reynolds Number: 100000
Density: 1100 kg/m^3 --> Reynolds Number: 110000
Density: 1200 kg/m^3 --> Reynolds Number: 120000


***Looping over two lists with zip()***

In [26]:
rho = [1.2, 1.1, 1.0]        # densities
V   = [50, 60, 70]           # velocities

for r, v in zip(rho, V):
    print(f"Density = {r}, Velocity = {v}")


Density = 1.2, Velocity = 50
Density = 1.1, Velocity = 60
Density = 1.0, Velocity = 70


In [27]:
# Looping over two lists without zip()

rho = [1.2, 1.1, 1.0]        # densities
V   = [50, 60, 70]           # velocities

for i in range(len(rho)):
    print(f"Density = {rho[i]}, Velocity = {V[i]}")


Density = 1.2, Velocity = 50
Density = 1.1, Velocity = 60
Density = 1.0, Velocity = 70


In [28]:
densities = [1.2, 1.1, 1.0]        # densities
velocities  = [50, 60, 70]           # velocities
S = 20     # wing area in m^2
CL = 0.5   # lift coefficient

for rho, V in zip(densities, velocities):
    L = 0.5 * rho * V**2 * S * CL
    print(f"Density = {rho}, Velocity: {V} m/s --> Lift: {L:.0f} N")


Density = 1.2, Velocity: 50 m/s --> Lift: 15000 N
Density = 1.1, Velocity: 60 m/s --> Lift: 19800 N
Density = 1.0, Velocity: 70 m/s --> Lift: 24500 N


# ***NESTED LOOP***

In [29]:
# Constants
S = 20     # wing area in m^2
CL = 0.5   # lift coefficient

densities = [1.2, 1.1, 1.0]        # densities
velocities = [50, 60, 70]          # velocities

# Nested loop: each density with all velocities
for rho in densities:
    for V in velocities:
        L = 0.5 * rho * V**2 * S * CL
        print(f"Density = {rho}, Velocity = {V} m/s --> Lift: {L:.0f} N")


Density = 1.2, Velocity = 50 m/s --> Lift: 15000 N
Density = 1.2, Velocity = 60 m/s --> Lift: 21600 N
Density = 1.2, Velocity = 70 m/s --> Lift: 29400 N
Density = 1.1, Velocity = 50 m/s --> Lift: 13750 N
Density = 1.1, Velocity = 60 m/s --> Lift: 19800 N
Density = 1.1, Velocity = 70 m/s --> Lift: 26950 N
Density = 1.0, Velocity = 50 m/s --> Lift: 12500 N
Density = 1.0, Velocity = 60 m/s --> Lift: 18000 N
Density = 1.0, Velocity = 70 m/s --> Lift: 24500 N


In [30]:
# Constants
S = 20     # wing area in m^2
CL = 0.5   # lift coefficient

densities = [1.2, 1.1, 1.0]        # densities
velocities = [50, 60, 70]          # velocities

# Nested loop with enumerate to number cases

for i, rho in enumerate(densities):      # outer loop over densities
    for j, V in enumerate(velocities):   # inner loop over velocities
        L = 0.5 * rho * V**2 * S * CL
        print(f" Density = {rho}, Velocity = {V} m/s --> Lift: {L:.0f} N")



 Density = 1.2, Velocity = 50 m/s --> Lift: 15000 N
 Density = 1.2, Velocity = 60 m/s --> Lift: 21600 N
 Density = 1.2, Velocity = 70 m/s --> Lift: 29400 N
 Density = 1.1, Velocity = 50 m/s --> Lift: 13750 N
 Density = 1.1, Velocity = 60 m/s --> Lift: 19800 N
 Density = 1.1, Velocity = 70 m/s --> Lift: 26950 N
 Density = 1.0, Velocity = 50 m/s --> Lift: 12500 N
 Density = 1.0, Velocity = 60 m/s --> Lift: 18000 N
 Density = 1.0, Velocity = 70 m/s --> Lift: 24500 N


# ***WHILE LOOP***

In [31]:
# Constants
S = 20
CL = 0.5
rho = 1.2
V = 50

# Lift threshold
threshold = 20000

# While loop
while True:
    L = 0.5 * rho * V**2 * S * CL
    print(f"Velocity = {V} m/s --> Lift = {L:.0f} N")

    if L > threshold:
        print("Lift exceeded threshold!")
        break  # exit the loop

    V += 5   # increase velocity each iteration
            # V = V + 5


Velocity = 50 m/s --> Lift = 15000 N
Velocity = 55 m/s --> Lift = 18150 N
Velocity = 60 m/s --> Lift = 21600 N
Lift exceeded threshold!


In [32]:
# Constants
rho = 10        # water density, kg/m^3
D = 0.05          # pipe diameter, m
mu = 0.001        # viscosity, Pa.s

# Initial velocity
V = 1

# While loop
while True:
    Re = (rho * V * D) / mu
    print(f"Velocity = {V} m/s --> Reynolds number = {Re:.0f}")

    if Re > 4000:
        print("Flow has become turbulent!")
        break  # stop the loop

    V += 1  # increment velocity


Velocity = 1 m/s --> Reynolds number = 500
Velocity = 2 m/s --> Reynolds number = 1000
Velocity = 3 m/s --> Reynolds number = 1500
Velocity = 4 m/s --> Reynolds number = 2000
Velocity = 5 m/s --> Reynolds number = 2500
Velocity = 6 m/s --> Reynolds number = 3000
Velocity = 7 m/s --> Reynolds number = 3500
Velocity = 8 m/s --> Reynolds number = 4000
Velocity = 9 m/s --> Reynolds number = 4500
Flow has become turbulent!


In [33]:
# Example: increase velocity until Re > 4000
rho = 10
D = 0.05
mu = 0.001
V = 1

Re = (rho * V * D) / mu
while Re <= 4000:
    print(f"Velocity = {V} m/s --> Re = {Re:.0f}")
    V += 1
    Re = (rho * V * D) / mu


Velocity = 1 m/s --> Re = 500
Velocity = 2 m/s --> Re = 1000
Velocity = 3 m/s --> Re = 1500
Velocity = 4 m/s --> Re = 2000
Velocity = 5 m/s --> Re = 2500
Velocity = 6 m/s --> Re = 3000
Velocity = 7 m/s --> Re = 3500
Velocity = 8 m/s --> Re = 4000


# ***math package***

In [34]:
import math
x = 5.0
print(math.sqrt(x))     # Square root → 2.236...
print(math.sin(math.radians(30)))   # Sine of 30° → 0.5
print(math.log(x))     # Natural log
print(math.exp(x))      # e^5
print(math.pi)        # π = 3.14159...
print(x * math.pi)

2.23606797749979
0.49999999999999994
1.6094379124341003
148.4131591025766
3.141592653589793
15.707963267948966


In [35]:
velocities = [50, 60, 70]
rho = 1.225
for V in velocities:
    q = 0.5 * rho * math.pow(V, 2)
    print(f"Velocity={V}, Dynamic Pressure={q}")


Velocity=50, Dynamic Pressure=1531.25
Velocity=60, Dynamic Pressure=2205.0
Velocity=70, Dynamic Pressure=3001.25


In [36]:
import math

velocities = [50, 60, 70]
q = 0.5 * math.pow(velocities, 2)   # ❌ ERROR


TypeError: must be real number, not list

In [ ]:
import math

velocities = [50, 60, 70]

for V in velocities:
    q = 0.5 * math.pow(V, 2)
    print(q)


# ***numpy***


In [37]:
import numpy as np

# Define matrices
A = np.array([[2, 3],
              [1, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Addition, Subtraction
print("A + B =\n", A + B)
print("A - B =\n", A - B)

# Matrix multiplication
print("A * B (elementwise) =\n", A * B)

print("A @ B (matrix product) =\n", A @ B)  # or np.dot(A,B)

print ("matrix product with np.dot =\n", np.dot(A,B))

# Inverse & Determinant of a Matrix
det = np.linalg.det(A)
inv = np.linalg.inv(A)

print(f"Determinant = {det:.0f}")
print("Inverse =\n", inv)


# Transpose
print("A^T =\n", A.T)

# Eigenvalues & Eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues =", eigvals)
print("Eigenvectors =\n", eigvecs)

A + B =
 [[ 7  9]
 [ 8 12]]
A - B =
 [[-3 -3]
 [-6 -4]]
A * B (elementwise) =
 [[10 18]
 [ 7 32]]
A @ B (matrix product) =
 [[31 36]
 [33 38]]
matrix product with np.dot =
 [[31 36]
 [33 38]]
Determinant = 5
Inverse =
 [[ 0.8 -0.6]
 [-0.2  0.4]]
A^T =
 [[2 1]
 [3 4]]
Eigenvalues = [1. 5.]
Eigenvectors =
 [[-0.9486833  -0.70710678]
 [ 0.31622777 -0.70710678]]


In [38]:
# Solving Linear Equations
# 2x+3y=8
# x+4y=7

A = np.array([[2, 3], [1, 4]])
b = np.array([8, 7])

solution = np.linalg.solve(A, b)
print("Solution [x, y] =", solution)


Solution [x, y] = [2.2 1.2]


In [39]:
# Finding Roots of a Polynomial
# p(x) = x^3−6x^2+11x−6

coeff = [1, -6, 11, -6]   # coefficients
roots = np.roots(coeff)
print("Roots =", roots)

# Polynomial Evaluation
# Check p(3.5):
val = np.polyval(coeff, 3.5)
print("p(2.5) =", val)

Roots = [3. 2. 1.]
p(2.5) = 1.875


In [52]:
# Random 3×3 matrix (values between 0 and 1)
rand  = np.random.rand(3,3)
print(rand)
# Zero / Ones / Identity
zeros = np.zeros((3,3))
ones  = np.ones((3,3))
I     = np.eye(3)

print(zeros)
print(ones)
print(I)

[[0.37793337 0.5405439  0.63653127]
 [0.87193482 0.47124128 0.57204795]
 [0.78356794 0.68449915 0.657059  ]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
# array creation
import numpy as np

# 1D array
a = np.array([1, 2, 3])
print(a)

print(a.shape)       # tuple: dimensions
print(a.size)        # total number of elements
print(a.ndim)        # number of dimensions
print(a.dtype)       # type of elements

[1 2 3]
[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3,)
3
1
int64
(3, 3)
9
2
int64


In [62]:
# 2D array
import numpy as np
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

print(b.shape)       # tuple: dimensions
print(b.size)        # total number of elements
print(b.ndim)        # number of dimensions
print(b.dtype)       # type of elements

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
int64


In [71]:
# 2D array
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print(c)

print(c.shape)       # tuple: dimensions
print(c.size)        # total number of elements
print(c.ndim)        # number of dimensions
print(c.dtype)       # type of elements


# Printing slices
print("First element:", c[0,0])
print("First row:", c[0,:])
print("Last row):", c[-1,:])
print("First column:", c[:, 0])
print("Second row:", c[1, :])
print("Submatrix from row 1 and column 1 onwards:\n", c[1:, 1:])

# Reshape to 1 row, 9 columns
c_reshaped = c.reshape(1, 9)
print("Reshaped to (1,9):\n", c_reshaped)

# Reshape to 9 rows, 1 column
c_reshaped2 = c.reshape(9, 1)
print("Reshaped to (9,1):\n", c_reshaped2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
9
2
int64
First element: 1
First row: [1 2 3]
Last row): [6 7 8]
First column: [1 4 6]
Second row: [4 5 6]
Submatrix from row 1 and column 1 onwards:
 [[5 6]
 [7 8]]
Reshaped to (1,9):
 [[1 2 3 4 5 6 6 7 8]]
Reshaped to (9,1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [6]
 [7]
 [8]]


In [76]:
# 2D array
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(c)


# Reshape to 1 row, 9 columns
c_reshaped = c.reshape(3, 4)
print("Reshaped to (1,9):\n", c_reshaped)

# Reshape to 9 rows, 1 column
c_reshaped2 = c.reshape(6, 2)
print("Reshaped to (9,1):\n", c_reshaped2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped to (1,9):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped to (9,1):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [41]:
# correct way with numpy

import numpy as np

velocities = np.array([50, 60, 70])   # Convert list to numpy array
q = 0.5 * velocities**2
print(q)


[1250. 1800. 2450.]


In [42]:
# list
velocities = [50, 60, 70]
print(velocities * 2)     # Here, *2 means repetition (concatenation),
                          # not multiplication.

# numpy array
import numpy as np

velocities = np.array([50, 60, 70])
print(velocities * 2)   # Here, *2 means element-wise multiplication

[50, 60, 70, 50, 60, 70]
[100 120 140]


In [43]:
# Case 1: ρ and V have same length (pairwise calculation)
import numpy as np

rho = np.array([1.2, 1.1, 1.0])    # densities
V   = np.array([50, 60, 70])       # velocities
S = 20     # wing area (m²)
CL = 0.5   # lift coefficient

L = 0.5 * rho * V**2 * S * CL
print(L)


[15000. 19800. 24500.]


In [77]:
# Case 2: All combinations of ρ and V
rho = np.array([1.2, 1.1, 1.0])   # 3 densities
V   = np.array([50, 60, 70])      # 3 velocities
S = 20
CL = 0.5

# Broadcasting: convert rho to column vector
L = 0.5 * rho.reshape(3, 1) * V**2 * S * CL  # or use rho[:, np.newaxis]
print(L)

# NumPy will happily give you a matrix of Lift values for all combinations of ρ and  V, but it won’t automatically label which value belongs to which pair


[[15000. 21600. 29400.]
 [13750. 19800. 26950.]
 [12500. 18000. 24500.]]


In [45]:
# Case 3: for loop with NumPy arrays

import numpy as np

rho = np.array([1.2, 1.1, 1.0])
V   = np.array([50, 60, 70])
S = 20
CL = 0.5

for r in rho:
    for v in V:
        L = 0.5 * r * v**2 * S * CL
        print(f"rho={r}, V={v}, Lift={L:.0f}")
# This code will also work using only for loops, without NumPy, by treating rho and V as Python lists.

rho=1.2, V=50, Lift=15000
rho=1.2, V=60, Lift=21600
rho=1.2, V=70, Lift=29400
rho=1.1, V=50, Lift=13750
rho=1.1, V=60, Lift=19800
rho=1.1, V=70, Lift=26950
rho=1.0, V=50, Lift=12500
rho=1.0, V=60, Lift=18000
rho=1.0, V=70, Lift=24500


# ***matplotlib***

In [ ]:
import numpy as np
x = np.linspace(0,10,100)
print(x)
y = np.arange(0,10,0.1)
print(y)

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(0,10,100) # linspace → stop is inclusive by default
y = np.sin(x)             # x = np.arange(0,10,0.1)
                          # arange → stop is exclusive
plt.plot(x,y)
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.title('Simple Plot')
plt.grid(True)
plt.show()
